# Generated by Django 5.2.5 on 2025-09-30 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="habit",
            name="days_of_week",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select specific days whena good habit should be performed.",
                to="habits.week",
                verbose_name="day(s) of week",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Enter the time when a habit "
                          "should be performed for the last "
                          "time per day. Only for good habits "
                          "that should be performed sever al times per day!",
                null=True,
                verbose_name="end time",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m x-y * * *", "every hour"),
                    ("m x-y/2 * * *", "every 2 hours"),
                    ("m x-y/3 * * *", "every 3 hours"),
                    ("m x,z,y * * *", "3 times per day"),
                    ("m x,y * * *", "2 times per day"),
                    ("m h * * *", "every day"),
                    ("m h */2 * *", "every 2 days"),
                    ("m h */3 * *", "every 3 days"),
                    ("m h * * d", "selected days"),
                ],
                default="m h * * *",
                help_text="Select how often a good habit "
                          "should be performed. NOTE! "
                          "A good habit should be performed "
                          "once a week at least.For good habits only!",
                null=True,
                verbose_name="frequency",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                help_text="Select whether a habit "
                          "is pleasant or not. "
                          "Only pleasant habits "
                          "can serve as rewards for good habits.",
                verbose_name="pleasant or not",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                help_text="Select whether you wantother users see your habit.",
                verbose_name="public or not",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a related pleasant habit(as a reward). For good habits only!",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="related habit",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Enter the reward for habit performance.",
                max_length=200,
                null=True,
                verbose_name="reward",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                blank=True,
                help_text="Enter the time when a "
                          "habitshould be performed."
                          "In case a habit should beperformed "
                          "several times per day, the end "
                          "timeshould also be selected.For "
                          "good habits only!",
                null=True,
                verbose_name="time",
            ),
        ),
    ]
